name := "hydrogen"
version := "0.3.0"
scalaVersion := "2.12.7"
organization := "com.hwaipy"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.5" % "test"
libraryDependencies += "org.jscience" % "jscience" % "4.3.1"
libraryDependencies += "org.scalanlp" %% "breeze" % "1.0-RC2"
libraryDependencies += "org.scalanlp" %% "breeze-natives" % "1.0-RC2"
libraryDependencies += "javax.servlet" % "javax.servlet-api" % "4.0.1"
scalacOptions ++= Seq("-feature")
scalacOptions ++= Seq("-deprecation")