name := "hydrogen"
version := "0.1.0"
scalaVersion := "2.12.1"
organization := "com.hwaipy"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.1" % "test"
libraryDependencies += "org.jscience" % "jscience" % "4.3.1"
